package com.project_agh.payrollmanagementsystem.entities;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a department within the organization.
 * <p>
 * This JPA entity maps to the "dzial" table in the database and holds core
 * information about a department, including its unique identifier, name, and description.
 * It uses Lombok annotations for automatic generation of boilerplate code
 * like getters, setters, and constructors.
 */
@Entity
@Table(name = "dzial")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Department {
    /**
     * The unique identifier for the department.
     * Mapped to the "id_dzial" column and configured as the primary key.
     * The value is auto-generated by the database upon persistence.
     */
    @Id
    @Column(name = "id_dzial", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the department.
     * Mapped to the "nazwa" column and must be unique across all departments.
     */
    @Column(name = "nazwa", unique = true)
    private String name;

    /**
     * A detailed description or notes about the department.
     * Mapped to the "opis" column.
     */
    @Column(name = "opis")
    private String description;
}