package com.project_agh.payrollmanagementsystem.entities;
import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a user role or access level within the Payroll Management System (e.g., ADMIN, USER).
 * <p>
 * This JPA entity maps to the "rola" table in the database and is used for
 * managing authorization and permissions across the system.
 * It utilizes Lombok annotations for automatic generation of standard methods.
 */
@Entity
@Table(name = "rola")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Role {

    /**
     * The unique identifier for the role.
     * Mapped to the "id_rola" column and configured as the primary key.
     * The value is auto-generated by the database upon persistence.
     */
    @Id
    @Column(name = "id_rola", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the role (e.g., "ROLE_ADMIN", "ROLE_EMPLOYEE").
     * Mapped to the "nazwa" column and must be unique.
     * Note: While the column is set to nullable in the DDL (@Column(..., nullable = true)),
     * it should ideally be non-null in production scenarios.
     */
    @Column(name = "nazwa", unique = true, nullable = true)
    private String name;

}